name: "🐞 バグ報告"
description: "不具合を報告するレポート"
labels:
  - "Type: Bug"
body:
  - type: textarea
    attributes:
      label: 概要
      description: |
        簡潔に不具合を説明してください。
        問題の理解に役立つスクリーンショットや動画、ログなどがあれば添付してください。
      placeholder: XXX画面でYYYを行った際にZZZが発生する。
    validations:
      required: true
  - type: textarea
    attributes:
      label: 期待する動作
      description: 簡潔に期待する動作を説明してください。
    validations:
      required: true
  - type: textarea
    attributes:
      label: 再現方法
      description: 事象の再現方法を記載してください。
      placeholder: |
        1. '...' メニューを開く
        2. '....' を選択する
        3. '....' に移動する
        4. エラーを確認する
    validations:
      required: true
  - type: textarea
    attributes:
      label: その他
      description: その他、不具合に関連する情報を入力してください。
